FROM node:14 as build-stage
# RUN npm install -g @vue/cli
WORKDIR /application
# COPY app/package*.json /application/
# RUN npm install @vue/cli-service
# RUN npm install
COPY app/* /application/
# RUN npm run build

